name: Build and Deploy Plex Media Server

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Upload on docker
    environment: prod
    runs-on: arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.docker-project }}/
          push: true
          tags: pagarme/${{ inputs.docker-project }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max